function output_filename = LTE_common_generate_output_filename(LTE_params,N_subframes)
% Utility funciton to generate the output filename for the reults file.
% Author: Josep Colom Ikuno, jcolom@nt.tuwien.ac.at
% (c) 2009 by INTHFT
% www.nt.tuwien.ac.at

% Code to generate the output filename
the_date = clock;

if strcmp(LTE_params.scheduler.cqi,'dynamic')
    cqi_string = '_dynamic';
else
    cqi_string = [ '_' sprintf('%d',LTE_params.scheduler.cqi) ];
end

output_filename = sprintf('cqi%s_%dre-tx_%dTTI_UL_delay_%3.1fMHz_%s_TX_mode%d_%dx%d_%s_freqoff%d_%s_%dTTI_%s_%04d%02d%02d_%02d%02d%02d',...
    cqi_string,...
    LTE_params.max_HARQ_retransmissions,...
    LTE_params.uplink_delay,...
    LTE_params.Bandwidth/1e6,...
    LTE_params.ChanMod_config.type,...
    LTE_params.UE_config.mode,...
    LTE_params.BS_config.nTx,...
    LTE_params.UE_config.nRX,...
    LTE_params.UE_config.receiver,...
    LTE_params.introduce_frequency_offset,...
    LTE_params.UE_config.rfo_correct_method,...
    N_subframes,...
    LTE_params.release,...
    the_date(1),...      % Date: year
    the_date(2),...      % Date: month
    the_date(3),...      % Date: day
    the_date(4),...      % Date: hour
    the_date(5),...      % Date: minutes
    floor(the_date(6))); % Date: seconds)
